<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="../../BuildingBlocks/InvestorAI.Infrastructure/InvestorAI.Infrastructure.csproj" />
		<EmbeddedResource Include="Sql/*.sql" LogicalName="Tenant.Migrations.%(Filename)%(Extension)" />
		<None Update="appsettings.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
	</ItemGroup>
</Project>
